include:
  - docker-compose-nginx.yml

services:
  api:
    build: .
    restart: unless-stopped
    expose:
      - 8000
    env_file:
      - .env.template
    depends_on:
      - postgres
      - nginx
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn src.adapter.driver.api.app:app --host 0.0.0.0 --port 8000'
    networks:
      - app-network

  migrations:
    build: .
    env_file:
      - .env.template
    depends_on:
      - postgres
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; alembic -c migrations/alembic/alembic.ini upgrade head"
    networks:
      - app-network

  postgres:
    image: postgres:16.0-alpine
    restart: unless-stopped
    # ports:
    #   - "5432:5432"
    volumes:
      - py_ports_adapters_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.template
    networks:
      - app-network

volumes:
  py_ports_adapters_postgres_data:

networks:
  app-network:
