services:
  api:
    build: .
    ports:
      - "8008:8000"
    env_file:
      - .env.template
    depends_on:
      - postgres
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn src.adapter.driver.api.app:app --host 0.0.0.0'

  migrations:
    build: .
    env_file:
      - .env.template
    depends_on:
      - postgres
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; alembic -c migrations/alembic/alembic.ini upgrade head"

  postgres:
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - py_ports_adapters_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.template

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

volumes:
  py_ports_adapters_postgres_data:
