include:
  - docker-compose-traefik.yml

services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - 8000:8000
    env_file:
      - .env.template
    depends_on:
      - postgres
      - reverse-proxy
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn src.adapter.driver.api.app:app --host 0.0.0.0 --port 8000'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)" # api.localhost:8000
      - "traefik.docker.network=proxy"
    networks:
      - proxy

  migrations:
    build: .
    env_file:
      - .env.template
    depends_on:
      - postgres
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; alembic -c migrations/alembic/alembic.ini upgrade head"
    networks:
      - proxy

  postgres:
    image: postgres:16.0-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - py_ports_adapters_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.template
    networks:
      - proxy

volumes:
  py_ports_adapters_postgres_data:
